=== StephenMcConnel/CarlaLegacy/PAWSStarterKit/Data/PAWSSKHtmlMapper.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v3.5 (http://www.xmlspy.com)-->
<!-- DTD for PAWS Starter Kit XML to HTML and code mappers -->
<!ENTITY nbsp "&#160;">
<!ENTITY % embedded "#PCDATA | br | category | contents | example | feature |
						 featureChart | file | help | i | ol | p | section | span |
			 template | templateName | tool | tree | u | ul">
<!ELEMENT br EMPTY>
<!ELEMENT button EMPTY>
<!ATTLIST button
	id ID #REQUIRED
	value (Cancel | OK | Yes | No) #REQUIRED
	goto CDATA #IMPLIED
>
<!ELEMENT buttons (button, codeInfo?, ruleInfo?, button, codeInfo?, ruleInfo?)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT codeInfo (#PCDATA)>
<!ELEMENT contents (#PCDATA)>
<!ELEMENT EnglishExample (exItem+)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT exItem (#PCDATA | u)*>
<!ATTLIST exItem
	label CDATA #IMPLIED
>
<!ELEMENT feature (#PCDATA)>
<!ELEMENT featureChart (featureRow)+>
<!ATTLIST featureChart
	types (yes | no) "yes"
	explanations (yes | no) "yes"
>
<!ELEMENT featureExplanation (#PCDATA)>
<!ELEMENT featureItem (#PCDATA)>
<!ELEMENT featureRow (featureType, featureItem, featureExplanation)+>
<!ELEMENT featureType (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ATTLIST file
	id ID #REQUIRED
	section CDATA #REQUIRED
>
<!ELEMENT form ((textBox | prompt | radioGroup | instruction | codeInfo | ruleInfo | introduction | EnglishExample)*, br?, buttons)>
<!ATTLIST form
	transparent (yes | no) "no"
	section CDATA #REQUIRED
>
<!ELEMENT help (#PCDATA)>
<!ATTLIST help
	href CDATA #REQUIRED
>
<!ELEMENT i (#PCDATA)>
<!ELEMENT groupName (#PCDATA)>
<!ATTLIST groupName
	dataItem CDATA #REQUIRED
	default CDATA #REQUIRED
	position (no | yesSpec | yesHead | yesHeadDiff) "no"
>
<!ELEMENT instruction (%embedded; | codeInfo | ruleInfo)*>
<!ATTLIST instruction
	id ID #IMPLIED
>
<!ELEMENT introduction (%embedded; | codeInfo | ruleInfo)*>
<!ELEMENT li (%embedded;)*>
<!ATTLIST li
	id ID #IMPLIED
>
<!ELEMENT ol (li+)>
<!ELEMENT p (%embedded;)*>
<!ATTLIST p
	style CDATA #IMPLIED
>
<!ELEMENT page (title, (introduction | EnglishExample | instruction)*, form)>
<!ELEMENT prompt (#PCDATA | category | i | span)*>
<!ATTLIST prompt
	id ID #IMPLIED
>
<!ELEMENT radio (%embedded;)*>
<!ATTLIST radio
	id ID #REQUIRED
	dataValue CDATA #REQUIRED
	checked (yes) #IMPLIED
>
<!ELEMENT radioGroup (groupName, prompt, radio, (radio | codeInfo | ruleInfo | radioGroup)*)>
<!ATTLIST radioGroup
	id ID #IMPLIED
>
<!ELEMENT ruleInfo (#PCDATA)>
<!ELEMENT span (%embedded;)*>
<!ATTLIST span
	id ID #IMPLIED
>
<!ELEMENT section (#PCDATA)>
<!ATTLIST section
	number CDATA #REQUIRED
>
<!ELEMENT textBox EMPTY>
<!ATTLIST textBox
	id ID #REQUIRED
	contenteditable (true | inherit | false) "inherit"
	dataItem CDATA #REQUIRED
	rows CDATA #IMPLIED
	cols CDATA #IMPLIED
>
<!ELEMENT title (#PCDATA | i)*>
<!ATTLIST title
	level CDATA #IMPLIED
>
<!ELEMENT template (#PCDATA)>
<!ELEMENT templateName (#PCDATA)>
<!ELEMENT tool (#PCDATA)>
<!ELEMENT tree (#PCDATA | br)*>
<!ELEMENT u (#PCDATA)>
<!ELEMENT ul (li+)>

=== StephenMcConnel/CarlaLegacy/PAWS/XMLPageDescriptions/NPMain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="NPMain">
	<title>Simple and Possessed Nominal Phrases</title>
	<introduction>Nominal phrases can be very complex, so they will be divided into four sections in this starter kit.  This section concentrates on those with common nouns as the lexical head.  We will consider modification by articles, demonstratives, quantifiers and degree words, adjective phrases, and possessors.   Nominal phrases headed by pronouns, proper names, demonstratives, and quantifiers are handled in <section number="6">Pronouns and Proper Names</section>.  The possibility of modification by pre/post-positional phrases is added in <section number="7">Pre/Post-positional Phrases</section> and modification by relative clauses is added in <section number="14">Relative Clauses</section>.</introduction>
	<introduction>Because there are so many positions needed for distinct sets of modifiers, we will use the expanded DP (determiner phrase) structure, rather than the simpler NP phrase structure.  These more complex tree structures will be built step-by-step from your answers to the questions here. You simply need to be aware that when you look at the tree structures generated, nominal phrases will have DPs on top of the NPs.  A simple English example is given here:
<tree>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DP&nbsp;<br/>
&nbsp;&nbsp;&nbsp;______|_______<br/>
&nbsp;Deg&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;D'&nbsp;<br/>
&nbsp;just&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;______|______<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Dem&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NP<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;those&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;N'&nbsp;<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_____|______<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AdjP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;N'&nbsp;&nbsp;<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;____|____<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Adj&nbsp;&nbsp;&nbsp;&nbsp;AdjP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;N'&nbsp;&nbsp;<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fine&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Adj&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;N&nbsp;<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;young&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;men&nbsp;<br/>
		</tree>
It may be difficult to understand the need for the change in English, because articles, demonstratives and possessors are mutually exclusive, but in many languages all three can occur in a single nominal phrase.  <help href="../Help/Cbgbtext.doc#DPHypothesis">(Click here to see more on the DP hypothesis.)</help>
	</introduction>
	<form section="np">
		<introduction>Many languages require agreement between at least some of the modifiers and the head noun.  While English only has number agreement, in other languages this agreement may also include animacy, class, or gender.  The grammar rules generated by this starter kit include the constraints for full agreement, but if your language only has partial or no agreement, you simply will not add those features to your lexical items.  In that case, the constraints will only apply vacuously.  Based on your answers below about the agreement system in your language, you will be instructed to add the appropriate features in the sections that follow.</introduction>
		<radioGroup>
			<groupName dataItem="agreeNumber" default="no">RAgreementNumber</groupName>
			<prompt>Think about the various modifiers that can be included in a nominal phrase, as in the tree structure above.  Does your language have any marking on articles, demonstratives, adjectives, etc. to show number agreement with the head noun?</prompt>
			<radio id="NPAgreeNoNumber" checked="yes" dataValue="no">No, there is no agreement, but number marking comes from the number or quantifier</radio>
			<radio id="NPAgreeYesNumber" checked="yes" dataValue="yes">Yes, like English, the various nominal modifiers may/must agree in number with the head noun</radio>
		</radioGroup>
		<radioGroup>
			<groupName dataItem="agreeOther" default="no">RAgreementOther</groupName>
			<prompt>Does your language have any additional features which may or must be marked on modifiers so that they agree with the head noun?</prompt>
			<radio id="NPAgreeNoOther" checked="yes" dataValue="no">No</radio>
			<radio id="NPAgreeYesAnimacy" checked="yes" dataValue="yesAnimacy">Yes, they may/must agree in animacy</radio>
			<radio id="NPAgreeYesClass" checked="yes" dataValue="yesClass">Yes, they may/must agree in class number </radio>
			<radio id="NPAgreeYesGender" checked="yes" dataValue="yesGender">Yes, they may/must agree in gender </radio>
		</radioGroup>
		<introduction>Besides agreement, nouns and their modifiers may be marked for case.  Therefore, we need to know what case system, if any, your language uses.  <br/>
			<br/>
The most common case system is nominative-accusative.  This is the system English has, though only pronouns are marked for case in English.  In a nominative-accusative system, subjects of both transitive and intransitive verbs are in nominative case, while direct objects are accusative case.  Possessors are genitive case.  The nominative pronouns in English are: <example>I, we, you, he, she, they</example>.  The accusative pronouns are: <example>me, us, you, him, her, them</example>.  The genitive pronouns include: <example>my, mine, our, ours, your, yours, his, her, hers, their, theirs</example>.  Therefore, we say <example>They hit him</example> and not <example>Them hit he</example>. <br/>
			<br/>
In an ergative-absolutive case system, subjects of transitive verbs are in the ergative case, while objects of transitive verbs and subjects of intransitive verbs are in the absolutive case.  The case of possessors is not set cross-linguistically, so if your language has an ergative-absolutive system, you will be asked about the case of possessors in that section. <br/>
			<br/>
Some languages are even more complex in that they normally have a nominative-accusative system but under some conditions the case system switches to ergative-absolutive.  This is called "split ergativity".  In this starter kit, the best we can do for these languages is to add all the rules allowing both case systems.  Afterward, the specific constraints needed for your language can be added to the rules.
</introduction>
		<radioGroup>
			<groupName dataItem="case" default="nominative">RCase</groupName>
			<prompt>Based on the description of the case systems above, which one is correct for your language?  Be sure to think about pronouns as well as nouns in considering your answer.</prompt>
			<radio id="NPCaseNone" checked="yes" dataValue="none">None: the exact same set of pronouns may be used in any position in the sentence and there is no marking on nouns or on any noun modifiers based on their position in the sentence</radio>
			<radio id="NPCaseNom" checked="yes" dataValue="nominative">Nominative-Accusative: like English, subjects of both transitive and intransitive verbs are the same, but objects of transitive verbs are different</radio>
			<radio id="NPCaseErg" checked="yes" dataValue="ergative">Ergative-Absolutive: subjects of intransitive verbs and objects of transitive verbs are the same, but subjects of transitive verbs are different</radio>
			<radio id="NPCaseSplit" checked="yes" dataValue="split">Split Ergativity: the language has a Nominative-Accusative system normally, but the Ergative-Absolutive system is used under certain conditions.</radio>
		</radioGroup>
		<br/>
		<buttons>
			<button id="NPMainBack" value="Back" goto="NPContents.htm"/>
			<button id="NPMainNext" value="Next" goto="NPContents.htm"/>
		</buttons>
	</form>
</page>

=== StephenMcConnel/CarlaLegacy/PAWS/XMLPageDescriptions/QPTesting.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="QPTesting">
	<title level="2">Quantifiers and QP - Testing</title>
	<form section="qp">
		<instruction>You need to make sure the cardinal number words in your lexicon will be mapped to the syntactic category <category>Num</category>.  Choose one of the following options, depending on your situation:
<ul>
				<li>If you already have numbers marked with the category <category>Num</category> in your lexicon, nothing
  more needs to be done.</li>
				<li>If numbers are mixed in with another category in the lexicon (e.g. adjectives), you either need to give them the category <category>Num</category> in your morphological parser, or add the feature <feature>makeNum</feature> to each appropriate entry in the lexicon so the category will be changed for the syntax.</li>
				<li>If you have numbers marked in your lexicon with a distinct category all their own, but it is different from <category>Num</category>, enter that category below so PAWS can map your morphological category to <category>Num</category>. <br/>
					<catMap id="QPCardinalNumberCategory" dataItem="cardinalNumberCategory">Num</catMap>
				</li>
			</ul>
			<br/>
Run the file qptest.txt through your morphological parser and then
run the syntactic parser on the output.  Check the log for the
results and note any changes you need to make to the lexicon or to
answers about the order of elements in the phrase structure
rules. Make the changes as needed and rerun.<br/>
			<br/>

(Note: some examples cannot be tested until you complete <section number="5">Simple and Possessed Nominal Phrases</section>.)<br/>
			<br/>

Please check off this section now in 'Contents' and then proceed to
<section number="3">Adverbs and AdvP</section> when you are ready.
</instruction>
		<br/>
		<buttons>
			<button id="QPTestingBack" value="Back" goto="QPCardinal.htm"/>
			<button id="QPTestingNext" value="Next" goto="Contents.htm"/>
		</buttons>
	</form>
</page>

=== StephenMcConnel/CarlaLegacy/PAWS/XMLPageDescriptions/NPNounCase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="NPNounCase">
	<title level="2">Nominal Phrase - Noun Case</title>
	<form section="np">
		<radioGroup>
			<groupName dataItem="nounCase" default="no">RNPCase</groupName>
			<prompt>Is case morphologically marked on nouns?</prompt>
			<radio id="NPCaseNo" dataValue="no">No, case is not marked at all, or only marked on the pronouns</radio>
			<radio id="NPCaseYes" dataValue="yes">Yes</radio>
			<radioGroup id="NPCaseYesTable">
				<groupName dataItem="nounCaseType" default="nomAcc">RNPCaseType</groupName>
				<prompt>Which system of case marking is used?</prompt>
				<radio id="NPCaseTypeNomAcc" dataValue="nomAcc">Nominative-accusative (where all subjects are nominative case and direct objects are accusative case)</radio>
				<radio id="NPCaseTypeErg" dataValue="erg">Ergative-absolutive (where subjects of transitive verbs are ergative case and subjects of intransitive verbs and objects of transitive verbs are absolutive case)</radio>
			</radioGroup>
		</radioGroup>
		<instruction id="NPCaseTypeNomAccInstruction">In the lexicon, mark the affix(es) that label nominative case with the feature <feature>nominative</feature>, along with any other agreement features they also mark.  Add the feature <feature>accusative</feature> to the affixes that mark accusative case.</instruction>
		<instruction id="NPCaseTypeErgInstruction">In the lexicon, mark the affix(es) that label ergative case with the feature <feature>ergative</feature>, along with any other agreement features they also mark.  Add the feature <feature>absolutive</feature> to the affixes that mark absolutive case.</instruction>
		<buttons>
			<button id="NPCaseBack" value="Back" goto="NPContents.htm"/>
			<button id="NPCaseNext" value="Next" goto="NPContents.htm"/>
		</buttons>
	</form>
</page>

=== StephenMcConnel/CarlaLegacy/Cabhab/Configurations/PAWS/XmlPageDescriptions/PNMain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="PNMain" count="1/3">
	<title>Proper Names</title>
	<introduction> In English, some names can stand alone, like <example>Sue</example> or <example>Russia</example>.  Others are like compound nouns, such as <example>George Washington</example>.  Proper names may also contain articles and/or pre/post-positional phrases, as in <example>the United States of America</example>.  Many languages require an article before a name.  Appositives, possibly including a possessor, as in <example>my son, David</example>, also occur.  In addition, proper names can be modified by adjectives and relative clauses, as in <example>the good, old USA</example> or <example>the Susan Welch that I know</example>.</introduction>
	<form section="prop">
		<prompt>Key your examples with simple and compound proper names, or those including articles, demonstratives, adjectives, and/or possessors here:</prompt>
		<textBox id="PNExample" dataItem="example"/>
		<br/>
		<br/>
		<prompt>Key your examples of proper names with pre/post-positional phrases here:</prompt>
		<textBox id="PNPPExample" dataItem="ppExample"/>
		<br/>
		<br/>
		<prompt>Key your examples of proper names modified by relative clauses here, included in simple full sentences:</prompt>
		<textBox id="PNRelClExample" dataItem="relClExample"/>
		<br/>
		<br/>
		<buttons>
			<button id="PNMainBack" value="Back" goto="Contents.htm"/>
			<button id="PNMainNext" value="Next" goto="PNCatMap.xml"/>
		</buttons>
	</form>
</page>

=== StephenMcConnel/CarlaLegacy/PAWS/XMLPageDescriptions/NPAdjP2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="NPAdjP2">
	<title level="2">Nominal Phrases - Adjp Modifiers Part 2</title>
	<form section="np">
<radioGroup>
	<groupName dataItem="adjpPos" default="unknown" position="yesSpec">RNPAdjPPos</groupName>
	<prompt>Where do adjective phrases occur with respect to the noun?</prompt>
	<radio id="NPAdjPPosBefore" dataValue="before">Before</radio>
	<radio id="NPAdjPPosAfter" dataValue="after">After</radio>
	<radio id="NPAdjPPosEitherSide" dataValue="either">Either side</radio>
<radioGroup id="NPAdjPPosEitherSideTable">
	<groupName dataItem="adjpEither" default="no">RNPAdjPPosEitherSideEither</groupName>
	<prompt>Can all the adjective phrases appear on either side of the noun?</prompt>
	<radio id="NPAdjPPosEitherSideEitherYes" dataValue="yes">Yes, there is no restriction</radio>
	<radio id="NPAdjPPosEitherSideEitherNo" dataValue="no">No, there are separate sets for each side</radio>
</radioGroup>
</radioGroup>
<instruction id="NPAdjPPosEitherSideEitherNoInstruction">In the lexicon, mark those adjectives which can only occur before the noun with the feature <feature>DP-initial</feature> and those which can only occur after the noun with the feature <feature>DP-final</feature>. Do not enter either feature on any adjective which can occur on either side.</instruction>
		<buttons>
			<button id="NPAdjp2Back" value="Back" goto="NPAdjP.htm"/>
			<button id="NPAdjp2Next" value="Next" goto="NPAgreement.htm"/>
		</buttons>
	</form>
</page>

=== StephenMcConnel/CarlaLegacy/Cabhab/Configurations/PAWS/Localizations/es/XmlPageDescriptions/PronPoss.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="PronPoss" count="2/8">
	<title level="2">Los pronombres - Los posesivos</title>
	<introduction>Muchos idiomas también tienen los pronombres posesivos que pueden usar sólos, por ejemplo <example>suys</example>, <example>mío</example>, <example>suyos</example> o <example>tuyo</example>  en español.
		Éstos son distintos de los que puedan presentarse en la posición del poseedor, tal como <example>su</example>, <example>mi</example>, <example>sus</example> o <example>tu</example>, que fueron ejemplificados con los pronombres personales en la página anterior.</introduction>
	<form section="pron">
		<radioGroup>
			<groupName dataItem="poss" default="no">RPronPoss</groupName>
			<prompt>¿Hay pronombres posesivos que se usan sólos como frase nominal en su idioma?</prompt>
			<radio id="PronPossNo" dataValue="no">No</radio>
			<radio id="PronPossYes" dataValue="yes">Sí</radio>
		</radioGroup>
		<prompt id="PronPossYesExamples" show="swPronPossYes">
			<br/>Escriba sus pronombres posesivos aquí, con cada uno en una nueva línea y seguida por un punto, comenzando con la primera persona, entonces segunda persona, entonces tercera persona:
		</prompt>
		<textBox id="PronPossExample" dataItem="possExample" show="swPronPossYes"/>
		<radioGroup id="PronPossAffix" show="swPronPossYes">
			<groupName dataItem="possAffix" default="no">RPronPossAffix</groupName>
			<prompt>
				<br/>¿Son construidos los pronombres posesivos que se usan sólos agregando uno o más afijos a otros pronombres (o a otra palabra)?</prompt>
			<radio id="PronPossAffixNo" dataValue="no">No, son palabras distintas</radio>
			<radio id="PronPossAffixYes" dataValue="yes">Sí, uno o más afijos se unen  para hacer otro pronombre (u otra palabra) en un posesivo</radio>
			<radio id="PronPossAffixBoth" dataValue="both">Sí, uno o más afijos se unen para hacer otro pronombre (u otra palabra) en un posesivo en algunos casos, pero algunas formas son palabras distintas</radio>
		</radioGroup>
		<instruction id="PronPossAffixNoInstruction" show="swPronPossAffixNo">In the lexicon, mark each possessive pronoun with the feature <feature>possessive</feature> and also all the relevant
<ul>
				<li>person (<feature>first</feature>, <feature>first_exclusive</feature>, <feature>first_inclusive</feature>, <feature>second</feature>, <feature>third</feature>),</li>
				<li>number (<feature>singular</feature>, <feature>dual</feature>, <feature>plural</feature>), </li>
				<li>gender (<feature>masculine</feature>, <feature>feminine</feature>, <feature>neuter</feature>) and </li>
				<li>animacy (<feature>animate</feature>, <feature>-animate</feature>, <feature>human</feature>, <feature>-human</feature>), features.</li>
			</ul>
		</instruction>
		<instruction id="PronPossAffixYesInstruction" show="swPronPossAffixYes">In the lexicon, add the feature <feature>possessive</feature> to the relevant affixes.</instruction>
		<instruction id="PronPossAffixBothInstruction" show="swPronPossAffixBoth">In the lexicon, add the feature <feature>possessive</feature> to the relevant affixes.  In addition, mark each stand alone possessive pronoun with the feature <feature>possessive</feature> and also all the relevant
<ul>
				<li>person (<feature>first</feature>, <feature>first_exclusive</feature>, <feature>first_inclusive</feature>, <feature>second</feature>, <feature>third</feature>),</li>
				<li>number (<feature>singular</feature>, <feature>dual</feature>, <feature>plural</feature>), </li>
				<li>gender (<feature>masculine</feature>, <feature>feminine</feature>, <feature>neuter</feature>) and </li>
				<li>animacy (<feature>animate</feature>, <feature>-animate</feature>, <feature>human</feature>, <feature>-human</feature>), features.</li>
			</ul>
		</instruction>
		<br/>
		<buttons>
			<button id="PronPossBack" value="Back" goto="PronMain.xml"/>
			<button id="PronPossNext" value="Next" goto="PronRefl.xml"/>
		</buttons>
	</form>
	<showWhen id="swPronPossYes">
		<whenRadio button="PronPossYes"/>
	</showWhen>
	<showWhen id="swPronPossAffixNo">
		<whenRadio button="PronPossYes"/>
		<and/>
		<whenRadio button="PronPossAffixNo"/>
	</showWhen>
	<showWhen id="swPronPossAffixYes">
		<whenRadio button="PronPossYes"/>
		<and/>
		<whenRadio button="PronPossAffixYes"/>
	</showWhen>
	<showWhen id="swPronPossAffixBoth">
		<whenRadio button="PronPossYes"/>
		<and/>
		<whenRadio button="PronPossAffixBoth"/>
	</showWhen>
</page>
