=== StephenMcConnel/CarlaLegacy/PAWSStarterKit/Data/PAWSSKHtmlMapper.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v3.5 (http://www.xmlspy.com)-->
<!-- DTD for PAWS Starter Kit XML to HTML and code mappers -->
<!ENTITY nbsp "&#160;">
<!ENTITY % embedded "#PCDATA | br | category | contents | example | feature |
						 featureChart | file | help | i | ol | p | section | span |
			 template | templateName | tool | tree | u | ul">
<!ELEMENT br EMPTY>
<!ELEMENT button EMPTY>
<!ATTLIST button
	id ID #REQUIRED
	value (Cancel | OK | Yes | No) #REQUIRED
	goto CDATA #IMPLIED
>
<!ELEMENT buttons (button, codeInfo?, ruleInfo?, button, codeInfo?, ruleInfo?)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT codeInfo (#PCDATA)>
<!ELEMENT contents (#PCDATA)>
<!ELEMENT EnglishExample (exItem+)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT exItem (#PCDATA | u)*>
<!ATTLIST exItem
	label CDATA #IMPLIED
>
<!ELEMENT feature (#PCDATA)>
<!ELEMENT featureChart (featureRow)+>
<!ATTLIST featureChart
	types (yes | no) "yes"
	explanations (yes | no) "yes"
>
<!ELEMENT featureExplanation (#PCDATA)>
<!ELEMENT featureItem (#PCDATA)>
<!ELEMENT featureRow (featureType, featureItem, featureExplanation)+>
<!ELEMENT featureType (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ATTLIST file
	id ID #REQUIRED
	section CDATA #REQUIRED
>
<!ELEMENT form ((textBox | prompt | radioGroup | instruction | codeInfo | ruleInfo | introduction | EnglishExample)*, br?, buttons)>
<!ATTLIST form
	transparent (yes | no) "no"
	section CDATA #REQUIRED
>
<!ELEMENT help (#PCDATA)>
<!ATTLIST help
	href CDATA #REQUIRED
>
<!ELEMENT i (#PCDATA)>
<!ELEMENT groupName (#PCDATA)>
<!ATTLIST groupName
	dataItem CDATA #REQUIRED
	default CDATA #REQUIRED
	position (no | yesSpec | yesHead | yesHeadDiff) "no"
>
<!ELEMENT instruction (%embedded; | codeInfo | ruleInfo)*>
<!ATTLIST instruction
	id ID #IMPLIED
>
<!ELEMENT introduction (%embedded; | codeInfo | ruleInfo)*>
<!ELEMENT li (%embedded;)*>
<!ATTLIST li
	id ID #IMPLIED
>
<!ELEMENT ol (li+)>
<!ELEMENT p (%embedded;)*>
<!ATTLIST p
	style CDATA #IMPLIED
>
<!ELEMENT page (title, (introduction | EnglishExample | instruction)*, form)>
<!ELEMENT prompt (#PCDATA | category | i | span)*>
<!ATTLIST prompt
	id ID #IMPLIED
>
<!ELEMENT radio (%embedded;)*>
<!ATTLIST radio
	id ID #REQUIRED
	dataValue CDATA #REQUIRED
	checked (yes) #IMPLIED
>
<!ELEMENT radioGroup (groupName, prompt, radio, (radio | codeInfo | ruleInfo | radioGroup)*)>
<!ATTLIST radioGroup
	id ID #IMPLIED
>
<!ELEMENT ruleInfo (#PCDATA)>
<!ELEMENT span (%embedded;)*>
<!ATTLIST span
	id ID #IMPLIED
>
<!ELEMENT section (#PCDATA)>
<!ATTLIST section
	number CDATA #REQUIRED
>
<!ELEMENT textBox EMPTY>
<!ATTLIST textBox
	id ID #REQUIRED
	contenteditable (true | inherit | false) "inherit"
	dataItem CDATA #REQUIRED
	rows CDATA #IMPLIED
	cols CDATA #IMPLIED
>
<!ELEMENT title (#PCDATA | i)*>
<!ATTLIST title
	level CDATA #IMPLIED
>
<!ELEMENT template (#PCDATA)>
<!ELEMENT templateName (#PCDATA)>
<!ELEMENT tool (#PCDATA)>
<!ELEMENT tree (#PCDATA | br)*>
<!ELEMENT u (#PCDATA)>
<!ELEMENT ul (li+)>

=== StephenMcConnel/CarlaLegacy/PAWS/XMLPageDescriptions/IPTrans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="IPTrans">
	<title level="2">Basic, Single-Clause Sentences - Transitive and Ditransitive Sentences</title>
	<introduction>Some examples of English transitive single-clause sentences are:</introduction>
	<EnglishExample>
		<exItem label="1.">The boy hit the ball.</exItem>
		<exItem label="2.">The boy will hit the ball.</exItem>
		<exItem label="3.">The boy might have hit the ball.</exItem>
		<exItem label="4.">The boy might have been hitting the ball.</exItem>
	</EnglishExample>
	<form section="ip">
		<prompt>Think of similar examples from your language and key them here:</prompt>
		<textBox id="IPExamplesExample" dataItem="example" cols="50"/>
<instruction>If a verb is transitive and it's object must always be present, add the feature <feature>transitive</feature> to its lexical entry.  Do not mark a verb like <example>eat</example> which may or may not have an overt object.</instruction>
		<introduction>Ditransitives can have the second object expressed as a PP or as a nominal phrase (DP).  Some languages, like English, allow both (via Dative Movement as in 4. below).  Some English examples of ditransitives are given below.</introduction>
		<EnglishExample>
			<exItem label="1.">The girl bought the present for her mother.</exItem>
			<exItem label="2.">The man sold his car for two thousand dollars.</exItem>
<exItem label="3.">The girl gave the gift to her mother.</exItem>
<exItem label="4.">The girl gave her mother the gift.</exItem>
		</EnglishExample>
		<prompt>Key your examples here:</prompt>
		<textBox id="IPExamplesDiExamples" dataItem="diExample" cols="50"/>
<radioGroup>
	<groupName dataItem="diCat" default="dp">RIPTransDiCat</groupName>
	<prompt>What syntactic category is the second object in a ditransitive in your language?</prompt>
	<radio id="IPTransDiCatPP" dataValue="pp">PP only</radio>
	<radio id="IPTransDiCatDP" dataValue="dp">DP only</radio>
	<radio id="IPTransDiCatBoth" dataValue="both">Either a DP or a PP (as in English)</radio>
</radioGroup>
<instruction>Any verbs which require the second object to always be present should be marked with the feature <feature>ditransitive</feature>.  Those which allow the second object, but it is optional, can be marked <feature>transitive</feature>.</instruction>
		<buttons>
			<button id="IPTransBack" value="Back" goto="IPContents.htm"/>
			<button id="IPTransNext" value="Next" goto="IPContents.htm"/>
		</buttons>
	</form>
</page>

=== StephenMcConnel/CarlaLegacy/PAWSStarterKit/XMLPageDescriptions/NPArtDem.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "C:\FieldWorks\ww\ww\PAWS\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="C:\FieldWorks\ww\ww\PAWS\Templates\PAWSSKHtmlMapper.xsl"?>
<page>
	<title level="2">Nominal Phrase - Articles and Demonstratives</title>
<introduction>Now consider articles and demonstratives.  In English, the articles are <example>a</example>, <example>an</example>, and <example>the</example>.  English demostratives include <example>this</example>, <example>that</example>, <example>these</example>, and <example>those</example>.  Some simple examples are:</introduction>
<EnglishExample>
	<exItem label="1.">a book.</exItem>
<exItem label="2.">an apple.</exItem>
<exItem label="3.">the book.</exItem>
<exItem label="4.">the books.</exItem>
<exItem label="5.">this apple.</exItem>
<exItem label="6.">those books.</exItem>
</EnglishExample>
<introduction>In English, articles and demonstratives do not co-occur in the same nominal phrase, and both occur before the noun.  They may be able to co-occur in your language, or they may occur in different positions with respect to the noun.  Therefore, we will give them different syntactic categories.</introduction>
	<form section="np">
<prompt>Key your examples here:</prompt>
<textBox id="NPExample" dataItem="example"/>
<instruction>Key some examples with both an article and a demonstrative in the box above, if grammatical, as well as some with each type alone.<br/><br/>
In the lexicon, mark articles with the feature <feature>Art</feature> and demonstratives with the feature <feature>Dem</feature>, to assure the proper category mapping.</instruction>
		<buttons>
			<button id="NPArtDemOK" value="OK" goto="NPArtCase.htm"/>
			<button id="NPArtDemCancel" value="Cancel"/>
		</buttons>
	</form>
</page>

=== StephenMcConnel/CarlaLegacy/PAWS/XMLPageDescriptions/QMain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="QMain">
	<title>Questions</title>
<introduction>This section considers the main clause and embedded clause varieties of Yes/No questions and content questions.  In English, main clause Yes/No questions are formed by moving an auxiliary verb in front of the subject.  Other languages use a Yes/No question marker word or particle or special complementizer instead of the fronted auxiliary.  This is the case in embedded Yes/No questions in English; no auxiliary fronting is allowed but <example>whether</example> or <example>if</example> fills the complementizer position.<br/><br/>
X-bar theory takes the complementizer to be the head of the phrase, so a CP sits on top of the IP for questions.  Sample trees for main clause and embedded Yes/No questions in English are shown here.
<tree>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;S<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CP<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C'<br/>
&nbsp;&nbsp;&nbsp;_________|_________<br/>
&nbsp;&nbsp;Aux&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;IP<br/>
&nbsp;&nbsp;are&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_________|_________<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I'<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;D'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VP<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_______|_______<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;V&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;PP<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;going&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pron&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;P'<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;you&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_____|_____<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;P&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DP<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;D'<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;___|____<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Art&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NP<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;the&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;N'<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;N<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;store<br/>
</tree>
<help href="../Help/Cbgbtext.doc#CPYesNoQuestions">Click here for more information about the CP phrase structure of Yes/No questions.</help><br/><br/>
Some English examples of main clause Yes/No questions are:
</introduction>
<EnglishExample>
	<exItem label="1.">Are you going to the store?</exItem>
<exItem label="2.">Will Sue buy the present for her mother?</exItem>
<exItem label="3.">Could the boy have hit the ball?</exItem>
</EnglishExample>
	<form section="q">
<prompt>Key similar examples of main clause Yes/No questions in your language here:</prompt>
<textBox id="QExample" dataItem="example" cols="50"/>
<prompt>Representative examples of English embedded Yes/No questions include:</prompt>
<EnglishExample>
	<exItem label="1.">I wonder whether she will come.</exItem>
	<exItem label="2.">I will know if she goes.</exItem>
	<exItem label="3.">Sue wonders whether the boy could have hit the ball.</exItem>
</EnglishExample>
<prompt>Key similar examples of embedded Yes/No questions in your language here.</prompt>
<textBox id="QEmbYNExample" dataItem="embYNExample" cols="50"/>
<instruction>Only certain verbs can take a question or sentential complement. In the lexicon, mark the verbs from your examples and any others that come to mind with the feature <feature>sentential</feature></instruction>
		<buttons>
			<button id="QBack" value="Back" goto="Contents.htm"/>
			<button id="QNext" value="Next" goto="QMainYN.htm"/>
		</buttons>
	</form>
</page>

=== StephenMcConnel/CarlaLegacy/PAWSStarterKit/XMLPageDescriptions/IPAux.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "C:\FieldWorks\ww\ww\PAWS\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="C:\FieldWorks\ww\ww\PAWS\Templates\PAWSSKHtmlMapper.xsl"?>
<page>
	<title level="2">Basic, Single-Clause Sentences - Auxiliaries</title>
	<introduction>Some languages have auxiliary elements that are separate words, and some can have more than one auxiliary element before the main verb.  Examples are given for English transitive single-clause sentences.</introduction>
	<EnglishExample>
		<exItem label="1.">The boy hit the ball.</exItem>
		<exItem label="2.">The boy will hit the ball.</exItem>
		<exItem label="3.">The boy might have hit the ball.</exItem>
		<exItem label="4.">The boy might have been hitting the ball.</exItem>
	</EnglishExample>
	<form section="ip">
		<prompt>Think of any similar examples from your language and key them here:</prompt>
		<textBox id="IPExamplesAuxExample" dataItem="auxExample" cols="50"/>
		<radioGroup>
			<groupName dataItem="aux" default="no">RIPAux</groupName>
			<prompt>Does your language have any auxiliary elements that are separate words?</prompt>
			<radio id="IPAuxNo" dataValue="no">No</radio>
			<radio id="IPAuxYes" dataValue="yes">Yes</radio>
			<radioGroup id="IPAuxRequiredTable">
				<groupName dataItem="auxRequired" default="no">RIPAuxRequired</groupName>
				<prompt>Is an auxiliary element required in every sentence?</prompt>
				<radio id="IPAuxRequiredNo" dataValue="no">No, it is optional</radio>
				<radio id="IPAuxRequiredYes" dataValue="yes">Yes, at least one is always required</radio>
			</radioGroup>
			<radioGroup id="IPAuxManyTable">
				<groupName dataItem="auxMany" default="no">RIPAuxMany</groupName>
				<prompt>Can there be more than one auxiliary in a single sentence?</prompt>
				<radio id="IPAuxManyNo" dataValue="no">No, only 1 is possible</radio>
				<radio id="IPAuxManyYes" dataValue="yes">Yes, more than one may occur before the verb phrase</radio>
			</radioGroup>
			<radioGroup id="IPAuxOrderTable">
				<groupName dataItem="auxOrder" default="no">RIPAuxOrder</groupName>
				<prompt>
					<span id="IPAuxOrderPromptVSO">After an auxiliary, is the normal VSO word order maintained?</span>
					<span id="IPAuxOrderPromptOSV">Before an auxiliary, is the normal OSV word order maintained?</span>
				</prompt>
				<radio id="IPAuxOrderYes" dataValue="yes">Yes, the order is always <span id="IPAuxOrderYesVSOPrompt">Aux V S then other elements</span>
					<span id="IPAuxOrderYesOSVPrompt">other elements then S V Aux</span>
				</radio>
				<radio id="IPAuxOrderNo" dataValue="no">No, the subject may come directly after the  <span id="IPAuxOrderNoVSOPrompt">Aux and before the verb</span>
					<span id="IPAuxOrderNoOSVPrompt">verb and before the Aux</span>
				</radio>
			</radioGroup>
		</radioGroup>
		<instruction id="IPAuxYesInstruction">The auxiliary elements need to have the category <category>Aux</category>.  If a particular form can also stand alone as the main verb in the sentence, you need to have two separate entries, one with the category <category>Aux</category> and one with the category <category>V</category>.  Choose one of the following options, depending on your situation:
<ul>
				<li>If you already have auxiliaries marked with the category <category>Aux</category> in your lexicon nothing more needs to be done.</li>
				<li>If you have auxiliaries marked in your lexicon with a distinct category all their own, but it is different from <category>Aux</category>, go to the <tool>Category Mapper</tool> and map your morphological category to <category>Aux</category>.</li>
				<li>If auxiliaries are mixed in with another category in the lexicon, you need to add the feature <category>Aux</category> to each appropriate entry so the category will be changed.</li>
			</ul>
		</instruction>
		<buttons>
			<button id="IPAuxOK" value="OK" goto="IPContents.htm"/>
			<button id="IPAuxCancel" value="Cancel"/>
		</buttons>
	</form>
</page>

=== StephenMcConnel/CarlaLegacy/PAWS/XMLPageDescriptions/CompMain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="CompMain">
	<title>Complement Clauses</title>
	<introduction>This section considers various types of embedded clauses which are complements of main verbs, such as the following examples from English.  (Embedded questions will be handled in <section number="11">Questions</section>.) </introduction>
<EnglishExample>
   <exItem label="1.">I believe that Jill is my friend.</exItem>
	<exItem label="2.">Jill insists that she is my friend.</exItem>
   <exItem label="3.">I expect that Joe will come to the party.</exItem>
  <exItem label="4.">I expect Joe to come to the party.</exItem>
   <exItem label="5.">I will persuade Joe to come to the party.</exItem>
   <exItem label="6.">Joe would hate for Sue to be at the party.</exItem>
   <exItem label="7.">Joe tried to come to the party.</exItem>
</EnglishExample>
<introduction>The examples illustrate that main verb selects one or more particular types of complement clauses which can occur gramatically.  For example, <example>try</example> cannot have a complement clause beginning with <example>that</example> and the subject of the embedded clause must be coreferent to the main clause subject and pro-dropped.  Further, <example>believe, insist</example> and <example>persuade</example> cannot have a complement clause beginning with <example>for</example> and none of the verbs above can have an embedded question complement.
<br/><br/>
A second point the examples illustrate is that the presence of a particular complementizer determines the finiteness of the embedded verb which follows it.  This evidence of subcategorization by the main verb for the complementizer and by the complementizer for the embedded verb form leads to the conclusion that the complementizer is the head of the embedded clause.  Therefore, within X-Bar Theory, embedded clauses which have complementizers are CPs, which sit on top of the IP.
<br/> <br/>A sample trees for example 1 is shown here: CHANGE FILE
<tree img="../TreeDescriptions/PawsMainYNQues.png"/>
		<br/>
When there is no complementizer present, as in examples 4, 5 and 7 above, the complement clause is simply an IP.  A sample tree for example 4 is shown here: CHANGE FILE
<tree img="../TreeDescriptions/PawsMainYNQues.png"/>
		<br/>
		<help href="../Help/Cbgbtext.doc#CPYesNoQuestions">Click here for more information about the CP phrase structure of embedded clauses.CHANGE REF</help>
	</introduction>
	<form section="q" transparent="yes">
		<br/>
		<buttons>
			<button id="QBack" value="Back" goto="Contents.htm"/>
			<button id="QNext" value="Next" goto="CompTesting.htm"/>
		</buttons>
	</form>
</page>

=== StephenMcConnel/CarlaLegacy/PAWS/XMLPageDescriptions/IPInflFeatures.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="IPInflFeatures">
	<title level="2">Basic, Single-Clause Sentences - Inflection Features</title>
	<introduction>Sentences normally include some kind of inflection on the verbs and possibly agreement between the subject, object and verb.</introduction>
	<instruction>Verbs and auxiliaries usually carry inflection features, such as tense, aspect, and/or mood.  In most cases, these features are added by affixes.  Add the appropriate features from the following chart to the relevant affixes and also to any auxiliaries or irregular verb forms: <br/>
	<featureChart explanations="no">
			<featureRow>
				<featureType>tense</featureType>
				<featureItem>present</featureItem>
				<featureExplanation/>
			</featureRow>
			<featureRow>
				<featureType/>
				<featureItem>past</featureItem>
				<featureExplanation/>
			</featureRow>
			<featureRow>
				<featureType/>
				<featureItem>future</featureItem>
				<featureExplanation/>
			</featureRow>
			<featureRow>
				<featureType>aspect</featureType>
				<featureItem>completive</featureItem>
				<featureExplanation/>
			</featureRow>
			<featureRow>
				<featureType/>
				<featureItem>continuative</featureItem>
				<featureExplanation/>
			</featureRow>
			<featureRow>
				<featureType/>
				<featureItem>habitual</featureItem>
				<featureExplanation/>
			</featureRow>
			<featureRow>
				<featureType/>
				<featureItem>imperfective</featureItem>
				<featureExplanation/>
			</featureRow>
			<featureRow>
				<featureType/>
				<featureItem>incompletive</featureItem>
				<featureExplanation/>
			</featureRow>
			<featureRow>
				<featureType/>
				<featureItem>perfective</featureItem>
				<featureExplanation/>
			</featureRow>
			<featureRow>
				<featureType/>
				<featureItem>potential</featureItem>
				<featureExplanation/>
			</featureRow>
			<featureRow>
				<featureType/>
				<featureItem>progressive</featureItem>
				<featureExplanation/>
			</featureRow>
			<featureRow>
				<featureType/>
				<featureItem>stative</featureItem>
				<featureExplanation/>
			</featureRow>
			<featureRow>
				<featureType>mood</featureType>
				<featureItem>declarative</featureItem>
				<featureExplanation/>
			</featureRow>
			<featureRow>
				<featureType/>
				<featureItem>imperative</featureItem>
				<featureExplanation/>
			</featureRow>
			<featureRow>
				<featureType/>
				<featureItem>interrogative</featureItem>
				<featureExplanation/>
			</featureRow>
			<featureRow>
				<featureType/>
				<featureItem>irrealis</featureItem>
				<featureExplanation/>
			</featureRow>
			<featureRow>
				<featureType/>
				<featureItem>realis</featureItem>
				<featureExplanation/>
			</featureRow>
		</featureChart>
	</instruction>
	<form section="ip" transparent="yes">
<br/>
		<buttons>
			<button id="IPInflFeaturesBack" value="Back" goto="IPContents.htm"/>
			<button id="IPInflFeaturesNext" value="Next" goto="IPAgrFeatures.htm"/>
		</buttons>
	</form>
</page>

=== StephenMcConnel/CarlaLegacy/PAWSStarterKit/XMLPageDescriptions/PronPoss.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "C:\Fieldworks\ww\ww\PAWS\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="C:\Fieldworks\ww\ww\PAWS\Templates\PAWSSKHtmlMapper.xsl"?>
<page>
	<title level="2">Pronouns and Proper Names - Possessive Pronouns</title>
	<introduction>Many languages also have possessive pronouns which can stand alone, such as <example>yours</example>, <example>mine</example>, <example>theirs</example>, <example>hers</example> in English.  These are distinct from those pronouns which can occur in possessor position, such as <example>your</example>, <example>my</example>, <example>their</example>, <example>her</example>, which should have already been handled in <section number="5.4">Possessors</section> and marked with the case of possessors.</introduction>
	<form section="pron">
	<radioGroup>
		<groupName dataItem="poss" default="yes">RPronPoss</groupName>
		<prompt>Does your language have stand alone possessive pronouns?</prompt>
		<radio id="PronPossNo" dataValue="no">No</radio>
		<radio id="PronPossYes" dataValue="yes">Yes</radio>
	</radioGroup>
	<prompt><span id="PronPossExamplePrompt">Key some examples here:</span></prompt>
	<textBox id="PronPossExample" dataItem="possExample"/>
	<radioGroup id="PronPossAffix">
		<groupName dataItem="possAffix" default="no">RPronPossAffix</groupName>
		<prompt>Are the stand alone possessive pronouns built by adding an affix to other pronouns?</prompt>
		<radio id="PronPossAffixNo" dataValue="no">No, they are distinct, stand alone words</radio>
		<radio id="PronPossAffixYes" dataValue="yes">Yes, one or more affixes are used to make another pronoun possessive</radio>
	</radioGroup>
	<instruction id="PronPossAffixNoInstruction">In the lexicon, mark each possessive pronoun with the feature <feature>possessive</feature> and also
<ul>
<li>all the relevant person (<feature>first</feature>, <feature>first_exclusive</feature>, <feature>first_inclusive</feature>, <feature>second</feature>, <feature>third</feature>),</li>
<li>number (<feature>singular</feature>, <feature>dual</feature>, <feature>plural</feature>), and</li>
<li>gender (<feature>masculine</feature>, <feature>feminine</feature>, <feature>neuter</feature>) features.</li>
</ul>
</instruction>
	<instruction id="PronPossAffixYesInstruction">In the lexicon, add the feature <feature>possessive</feature> to the relevant affixes.</instruction>
		<buttons>
			<button id="PronPossOK" value="OK" goto="PronIndefinite.htm"/>
			<button id="PronPossCancel" value="Cancel"/>
		</buttons>
	</form>
</page>
