=== StephenMcConnel/CarlaLegacy/PAWSStarterKit/Data/PAWSSKHtmlMapper.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v3.5 (http://www.xmlspy.com)-->
<!-- DTD for PAWS Starter Kit XML to HTML and code mappers -->
<!ENTITY nbsp "&#160;">
<!ENTITY % embedded "#PCDATA | br | category | contents | example | feature |
						 featureChart | file | help | i | ol | p | section | span |
			 template | templateName | tool | tree | u | ul">
<!ELEMENT br EMPTY>
<!ELEMENT button EMPTY>
<!ATTLIST button
	id ID #REQUIRED
	value (Cancel | OK | Yes | No) #REQUIRED
	goto CDATA #IMPLIED
>
<!ELEMENT buttons (button, codeInfo?, ruleInfo?, button, codeInfo?, ruleInfo?)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT codeInfo (#PCDATA)>
<!ELEMENT contents (#PCDATA)>
<!ELEMENT EnglishExample (exItem+)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT exItem (#PCDATA | u)*>
<!ATTLIST exItem
	label CDATA #IMPLIED
>
<!ELEMENT feature (#PCDATA)>
<!ELEMENT featureChart (featureRow)+>
<!ATTLIST featureChart
	types (yes | no) "yes"
	explanations (yes | no) "yes"
>
<!ELEMENT featureExplanation (#PCDATA)>
<!ELEMENT featureItem (#PCDATA)>
<!ELEMENT featureRow (featureType, featureItem, featureExplanation)+>
<!ELEMENT featureType (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ATTLIST file
	id ID #REQUIRED
	section CDATA #REQUIRED
>
<!ELEMENT form ((textBox | prompt | radioGroup | instruction | codeInfo | ruleInfo | introduction | EnglishExample)*, br?, buttons)>
<!ATTLIST form
	transparent (yes | no) "no"
	section CDATA #REQUIRED
>
<!ELEMENT help (#PCDATA)>
<!ATTLIST help
	href CDATA #REQUIRED
>
<!ELEMENT i (#PCDATA)>
<!ELEMENT groupName (#PCDATA)>
<!ATTLIST groupName
	dataItem CDATA #REQUIRED
	default CDATA #REQUIRED
	position (no | yesSpec | yesHead | yesHeadDiff) "no"
>
<!ELEMENT instruction (%embedded; | codeInfo | ruleInfo)*>
<!ATTLIST instruction
	id ID #IMPLIED
>
<!ELEMENT introduction (%embedded; | codeInfo | ruleInfo)*>
<!ELEMENT li (%embedded;)*>
<!ATTLIST li
	id ID #IMPLIED
>
<!ELEMENT ol (li+)>
<!ELEMENT p (%embedded;)*>
<!ATTLIST p
	style CDATA #IMPLIED
>
<!ELEMENT page (title, (introduction | EnglishExample | instruction)*, form)>
<!ELEMENT prompt (#PCDATA | category | i | span)*>
<!ATTLIST prompt
	id ID #IMPLIED
>
<!ELEMENT radio (%embedded;)*>
<!ATTLIST radio
	id ID #REQUIRED
	dataValue CDATA #REQUIRED
	checked (yes) #IMPLIED
>
<!ELEMENT radioGroup (groupName, prompt, radio, (radio | codeInfo | ruleInfo | radioGroup)*)>
<!ATTLIST radioGroup
	id ID #IMPLIED
>
<!ELEMENT ruleInfo (#PCDATA)>
<!ELEMENT span (%embedded;)*>
<!ATTLIST span
	id ID #IMPLIED
>
<!ELEMENT section (#PCDATA)>
<!ATTLIST section
	number CDATA #REQUIRED
>
<!ELEMENT textBox EMPTY>
<!ATTLIST textBox
	id ID #REQUIRED
	contenteditable (true | inherit | false) "inherit"
	dataItem CDATA #REQUIRED
	rows CDATA #IMPLIED
	cols CDATA #IMPLIED
>
<!ELEMENT title (#PCDATA | i)*>
<!ATTLIST title
	level CDATA #IMPLIED
>
<!ELEMENT template (#PCDATA)>
<!ELEMENT templateName (#PCDATA)>
<!ELEMENT tool (#PCDATA)>
<!ELEMENT tree (#PCDATA | br)*>
<!ELEMENT u (#PCDATA)>
<!ELEMENT ul (li+)>

=== StephenMcConnel/CarlaLegacy/PAWS/XMLPageDescriptions/AdvPManner.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by Andy Black (SIL International) -->
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="AdvPManner">
	<title level="2">Adverbs and AdvP - Manner Adverbs</title>
	<introduction>Manner adverbs directly modify the verb and usually end in <example>-ly</example> in English.  They do not seem to have clear
counterparts of other phrase types, except possibly some comparatives,
such as <example>as fast as he could</example>.  (Comparatives will be dealt with in <section number="15">Coordination Constructions</section>.)  In English,
manner adverbs can be modified by <example>very</example>
and <example>so</example>, as in:
</introduction>
	<EnglishExample>
		<exItem label="1.">very quickly.</exItem>
		<exItem label="2.">so slowly.</exItem>
		<exItem label="3.">very well.</exItem>
	</EnglishExample>
	<form section="advp">
		<prompt>Key examples of how your language expresses manner here:</prompt>
		<textBox id="AdvPMannerExample" dataItem="mannerExample"/>
<br/> <br/>
<radioGroup>
	<groupName dataItem="mannerType" default="word">RAdvPMannerType</groupName>
	<prompt>Some languages do not have separate words, but rather use affixes to express manner.  Does your language have any manner adverbs which are separate words?</prompt>
	<radio id="AdvPMannerTypeWord" dataValue="word">Yes</radio>
	<radio id="AdvPMannerTypeAffix" dataValue="affix">No, they are all written as part of the verb</radio>
</radioGroup>
		<instruction id="AdvPMannerTypeWordInstruction" show="swAdvPMannerTypeWord">In the lexicon, key the feature <feature>manner</feature>
on all adverbs that express manner.
</instruction>
<br/>
		<buttons>
			<button id="AdvPMannerExamplesBack" value="Back" goto="AdvPLocative.htm"/>
			<button id="AdvPMannerExamplesNext" value="Next" goto="AdvPReason.htm"/>
		</buttons>
	</form>
<showWhen id="swAdvPMannerTypeWord">
	<whenRadio button="AdvPMannerTypeWord"></whenRadio>
</showWhen>
</page>

=== StephenMcConnel/CarlaLegacy/PAWSStarterKit/XMLPageDescriptions/IPAgrFeatures.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "C:\FieldWorks\ww\ww\PAWS\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="C:\FieldWorks\ww\ww\PAWS\Templates\PAWSSKHtmlMapper.xsl"?>
<page>
	<title level="2">Basic, Single-Clause Sentences - Agreement Features</title>
<instruction>Verbs and auxiliaries may also carry agreement features that force agreement with the subject, and sometimes also with the direct object.  Key the appropriate features on the relevant affixes.  In the case of animacy, this is most likely not an affix but a property of the individual verbâ€™s semantics whether its subject and/or object must be animate, so those features will need to be keyed on the verb entry.
<featureChart>
<featureRow>
<featureType>person</featureType>
<featureItem>first_subjectfirst_object</featureItem>
<featureExplanation>the subject must be first personthe object must be first person</featureExplanation>
</featureRow>
<featureRow>
<featureType/>
<featureItem>first_exclusive_subjectfirst_exclusive_object</featureItem>
<featureExplanation>the subject must be first person exclusivethe object must be first person exclusive</featureExplanation>
</featureRow>
<featureRow>
<featureType/>
<featureItem>first_inclusive_subjectfirst_inclusive_object</featureItem>
<featureExplanation>the subject must be first person inclusivethe object must be first person inclusive</featureExplanation>
</featureRow>
<featureRow>
<featureType/>
<featureItem>second_subjectsecond_object</featureItem>
<featureExplanation>the subject must be second personthe object must be second person</featureExplanation>
</featureRow>
<featureRow>
<featureType/>
<featureItem>third_subjectthird_object</featureItem>
<featureExplanation>the subject must be third personthe object must be third person</featureExplanation>
</featureRow>
<featureRow>
<featureType>number</featureType>
<featureItem>singular_subjectsingular_object</featureItem>
<featureExplanation>the subject must be singularthe object must be singular</featureExplanation>
</featureRow>
<featureRow>
<featureType/>
<featureItem>dual_subjectdual_object</featureItem>
<featureExplanation>the subject must be dualthe object must be dual</featureExplanation>
</featureRow>
<featureRow>
<featureType/>
<featureItem>plural_subjectplural_object</featureItem>
<featureExplanation>the subject must be pluralthe object must be plural</featureExplanation>
</featureRow>
<featureRow>
<featureType>gender</featureType>
<featureItem>masculine_subjectmasculine_object</featureItem>
<featureExplanation>the subject must be masculinethe object must be masculine</featureExplanation>
</featureRow>
<featureRow>
<featureType/>
<featureItem>feminine_subjectfeminine_object</featureItem>
<featureExplanation>the subject must be femininethe object must be feminine</featureExplanation>
</featureRow>
<featureRow>
<featureType/>
<featureItem>neuter_subjectneuter_object</featureItem>
<featureExplanation>the subject must be neuterthe object must be neuter</featureExplanation>
</featureRow>
<featureRow>
<featureType>animacy</featureType>
<featureItem>animate_subjectanimate_object</featureItem>
<featureExplanation>the subject must be animatethe object must be animate</featureExplanation>
</featureRow>
<featureRow>
<featureType/>
<featureItem>-animate_subject-animate_object</featureItem>
<featureExplanation>the subject must be inanimatethe object must be inanimate</featureExplanation>
</featureRow>
<featureRow>
<featureType>class</featureType>
<featureItem>class_##_subjectclass_##_object</featureItem>
<featureExplanation>(replace ## with the class number up to 99)</featureExplanation>
</featureRow>
</featureChart>

</instruction>
	<form section="ip" transparent="yes">
		<buttons>
			<button id="IPAgrFeaturesOK" value="OK" goto="IPContents.htm"/>
			<button id="IPAgrFeaturesCancel" value="Cancel"/>
		</buttons>
	</form>
</page>

=== StephenMcConnel/CarlaLegacy/PAWS/XMLPageDescriptions/AdvClFeatures.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="AdvClFeatures">
	<title level="2">Adverbial Clauses - Examples and Features</title>
	<form section="advcl">
		<prompt>Key similar examples of temporal adverbial clauses in your language, included in (simple) full sentences here:</prompt>
		<textBox id="AdvlClTemporalExample" dataItem="tempSentExample" cols="50"/>
		<br/>
		<radioGroup>
			<groupName dataItem="advOrNPPos" default="unknown" position="yesHeadDiff">RAdvOrNPPos</groupName>
			<prompt>Where does an adverb or nominal phrase complement occur with respect to the head adverb?</prompt>
			<radio id="AdvClAdvOrNPPosBefore" dataValue="before">Before the adverb</radio>
			<radio id="AdvClAdvOrNPPosAfter" dataValue="after">After the adverb</radio>
			<radio id="AdvClAdvOrNPPosEither" dataValue="either">On either side</radio>
		</radioGroup>
		<br/>
		<instruction>In the lexicon, add the following features to the adverb entry, in addition to the feature <feature>temporal</feature>.  Note that the first two features can be added to the same entry, or either or both can be added to the third or fourth sets of features.
<ul>
				<li>If the adverb may have another adverb as its complement, add the feature <feature>takes_Adv</feature>.</li>
				<li>If the adverb may have a nominal phrase complement, add the feature <feature>takes_DP</feature>.</li>
				<li>If the adverb may have an IP complement, add the features <feature>sentential embedded_finite</feature>.</li>
				<li>If the adverb requires a complementizer to be present in its sentential complement (CP), add the features <feature>sentential embedded_finite embedded_CP</feature>.</li>
			</ul>
		</instruction>
		<br/>
		<introduction>Turning now to adverbial phrases or clauses which express reason or purpose, we find adverbs which stand alone, such as <example>therefore</example> and <example>so</example>, along with those that take various types of complement clauses.  (Examples such as <example>for this reason</example> and <example>on purpose</example> should work based on your answers in <section number="8">Pre/post-positional Phrases</section>.)
</introduction>
		<EnglishExample>
			<exItem>English examples of reason or purpose adverbs which take clausal complements include:</exItem>
			<exItem label="1.">John rushed to the hospital [because Sue was in an accident].</exItem>
			<exItem label="2.">[Since Jill said that she likes him], Joe smiles all the time.</exItem>
			<exItem label="3.">Bill rushed to the airport [so that he could see Kay before she left].</exItem>
			<exItem label="4.">The troops threw grenades at the enemy [in order to escape].</exItem>
			<exItem label="5.">The troops threw grenades at the enemy [in order for the prisoners to escape].</exItem>
		</EnglishExample>
		<introduction>In the examples above, <example>because</example> and <example>since</example> take only finite IP complements and <example>so</example> takes a finite CP complement.  In contrast, <example>in order</example> takes either a nonfinite IP with a pro-dropped subject or a nonfinite CP complement.  This is the same subcategorization as shown for <example>like</example> and <example>hate</example> in <section number="10">Complement Clauses</section>.  <br/>
			<br/>(Note again that if your language has any multi-word forms, like <example>in order</example>, they need be handled as a single lexical entry using <tool>Join Compound</tool>.)
 </introduction>
		<br/>
		<prompt>The examples you keyed in section 3 are shown below.  You may add any additional examples in (simple) full sentences as well.</prompt>
		<textBox id="AdvPReasonExample" section="advp" dataItem="reasonExample" cols="50"/>
		<br/>
		<br/>
		<instruction>In the lexicon, add the following features to the adverb entry, in addition to the feature <feature>reason</feature>.
<ul>
				<li>If the adverb may have a finite IP complement, add the features <feature>sentential embedded_finite</feature>.</li>
				<li>If the adverb requires a complementizer to be present in its finite sentential complement (CP), add the features <feature>sentential embedded_finite embedded_CP</feature>.</li>
				<li>If the adverb requires either a nonfinite IP with a pro-dropped subject or a nonfinite CP complement, add the features <feature>sentential embedded_-finite embedded_IPpro-dropOrCP</feature>.</li>
			</ul>
		</instruction>
		<br/>
		<buttons>
			<button id="AdvClFeaturesBack" value="Back" goto="AdvClMain.htm"/>
			<button id="AdvClFeaturesNext" value="Next" goto="AdvClTesting.htm"/>
		</buttons>
	</form>
</page>

=== StephenMcConnel/CarlaLegacy/PAWS/XMLPageDescriptions/IPTesting.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by Andy Black (SIL International) -->
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="IPTesting">
	<title level="2">Basic, Single-Clause Sentences - Testing</title>
	<form section="ip">
		<instruction id="IPAuxYesInstruction" show="swAuxYes">The auxiliary elements need to have the category <category>Aux</category>.  If a particular form can also stand alone as the main verb in the sentence, you need to have two separate entries, one with the category <category>Aux</category> and one with the category <category>V</category>.  Choose one of the following options, depending on your situation:
<ul>
				<li>If you already have auxiliaries marked with the category <category>Aux</category> in your lexicon nothing more needs to be done.</li>
				<li>If auxiliaries are mixed in with another category in the lexicon, you either need to give them the category <category>Aux</category> in your morphological parser, or add the feature <feature>makeAux</feature> to each appropriate entry in the lexicon so the category will be changed for the syntax.</li>
				<li>If you have auxiliaries marked in your lexicon with a distinct category all their own, but it is different from <category>Aux</category>, enter that category below so PAWS can map your morphological category to <category>Aux</category>.<br/>
					<catMap id="IPAuxCategory" dataItem="auxCategory">Aux</catMap>
				</li>
			</ul>
		</instruction>
		<instruction>You need to make sure the verbs in your lexicon will be mapped to the syntactic category <category>V</category>.  Choose one of the following options, depending on your situation:
<ul>
				<li>If you already have verbs marked with the category <category>V</category> in your lexicon, nothing
  more needs to be done.</li>
				<li>If verbs are mixed in with another category in the lexicon, you either need to give them the category <category>V</category> in your morphological parser, or add the feature <feature>makeV</feature> to each appropriate entry in the lexicon so the category will be changed for the syntax.</li>
				<li>If you have verbs marked in your lexicon with a distinct category all their own, but it is different from <category>V</category>, enter that category below so PAWS can map your morphological category to <category>V</category>. <br/>
					<catMap id="IPVerbCategory" dataItem="verbCategory">V</catMap>
				</li>
			</ul>
			<br/>
			<p>Run the file <file id="IPTestingFile" section="IP">iptest.txt</file> through your morphological parser and then
run the syntactic parser on the output.  Check the log for the
results and note any changes you need to make to the lexicon or to
answers about the order of elements in the phrase structure
rules. Make the changes as needed and rerun.  The examples with nonfinite auxiliaries in embedded clauses will not be able to be tested until <section number="10">Complement Clauses</section> is completed. </p>
			<p>
Please check off this section now in 'Contents' and then proceed to
<section number="10">Complement Clauses</section> when you are ready.</p>
		</instruction>
		<br/>
		<buttons>
			<button id="IPTestingBack" value="Back" goto="IPContents.htm"/>
			<button id="IPTestingNext" value="Next" goto="IPContents.htm"/>
		</buttons>
	</form>
	<showWhen id="swAuxYes">
		<whenValue element="ip" attr="aux" value="yes"/>
	</showWhen>
</page>

=== StephenMcConnel/CarlaLegacy/PAWSStarterKit/XMLPageDescriptions/QPDegree2.xml
<!DOCTYPE page SYSTEM "C:\FieldWorks\ww\ww\PAWS\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="C:\FieldWorks\ww\ww\PAWS\Templates\PAWSSKHtmlMapper.xsl"?>
<?xml-stylesheet type="text/xsl" href="C:\FieldWorks\ww\ww\PAWS\Templates\PAWSSKCodeMapper.xsl"?>
<page>
  <title level="2">Quantifiers and QP - Degree Words (Part 2)</title>
  <form>
	<prompt>Key your examples containing degree words here:</prompt>
	<textBox id="QPDegreeExample"/>
	<radioGroup>
	  <groupName>RDegree</groupName>
	  <prompt>Based on these examples, where do the degree words occur with respect to the quantifier?</prompt>
	  <radio id="QPDegreeBefore" checked="yes">Before the quantifier</radio>
	  <ruleInfo>Before is QP Option 2.</ruleInfo>
	  <codeInfo>Before is Spec-initial default and Spec-internal default.</codeInfo>
	  <radio id="QPDegreeAfter">After the quantifier</radio>
	  <ruleInfo>After is QP Option 3.</ruleInfo>
	  <codeInfo>After is Spec-final default.</codeInfo>
	  <radio id="QPDegreeEitherSide">On either side of the quantifier</radio>
	  <ruleInfo>Either is QP Option 4 (no matter what the answer is to next question).</ruleInfo>
	  <codeInfo>Following is greyed out unless the either button is checked</codeInfo>
	  <radioGroup id="QPDegreeEitherSideTable">
		<groupName>RDegreeEitherSide</groupName>
		<prompt>Can all the degree words appear on either side of the quantifier?</prompt>
		<radio id="QPDegreeEitherYes" checked="yes">Yes, there is no restriction</radio>
		<radio id="QPDegreeEitherNo">No, there are separate sets for each side</radio>
		<codeInfo>End of greyed out section</codeInfo>
	  </radioGroup>
	</radioGroup>
	<instruction>In the lexicon, mark this type of quantifier
with the feature <feature>Q</feature>.  This will change
their category to <category>Q</category> for the syntax.  If a particular quantifier can
only go with plural nouns, add the feature <feature>plural</feature> to that entry.  Also, mark any words
which can modify them with the features <feature>Deg
modifies_Q</feature>.<codeInfo>For the No answer to either side:</codeInfo>
	  <span id="QPDegreeEitherNoInstruction">Those which can only occur before the quantifier
also need to have the feature <feature>QP-initial</feature>
and those which can only occur after the quantifier also need the
feature <feature>QP-final</feature>.  Do not enter either
feature <feature>QP-initial</feature> or <feature>QP-final</feature> on any degree words which can occur on
either side.</span>
	  <codeInfo>end of For the No answer to either side:</codeInfo>Note that these degree words will most likely not be the
same as the ones which can modify an NP above.</instruction>
	<buttons>
	  <button id="QPDegree2OK" value="OK" goto="QPCardinal.htm"/>
	  <button id="QPDegree2Cancel" value="Cancel"/>
	</buttons>
  </form>
</page>

=== StephenMcConnel/CarlaLegacy/PAWS/XMLPageDescriptions/PronAgr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="PronAgr">
	<title level="2">Pronouns and Proper Nouns - Pronoun Agreement</title>
<instruction>Add the relevant agreement features to each pronoun in the lexicon, as shown in the chart.  If a pronoun is not specified for a particular type of agreement feature, do not add any feature of that type.<br/><br/>
<featureChart>
	<featureRow>
		<featureType>person</featureType>
		<featureItem>first</featureItem>
		<featureExplanation>first person, with no exclusive-inclusive distinction</featureExplanation>
</featureRow>
<featureRow>
	<featureType>&nbsp;</featureType>
	<featureItem>first_exclusive</featureItem>
	<featureExplanation>first person, cannot include the hearer</featureExplanation>
</featureRow>
	<featureRow>
		<featureType>&nbsp;</featureType>
		<featureItem>first_inclusive</featureItem>
		<featureExplanation>first person, and including the hearer</featureExplanation>
	</featureRow>
	<featureRow>
		<featureType>&nbsp;</featureType>
		<featureItem>second</featureItem>
		<featureExplanation>second person</featureExplanation>
	</featureRow>
	<featureRow>
		<featureType>&nbsp;</featureType>
		<featureItem>third</featureItem>
		<featureExplanation>third person</featureExplanation>
	</featureRow>
	<featureRow>
		<featureType>number</featureType>
		<featureItem>singular</featureItem>
		<featureExplanation>singular in number</featureExplanation>
	</featureRow>
	<featureRow>
		<featureType>&nbsp;</featureType>
		<featureItem>dual</featureItem>
		<featureExplanation>two in number</featureExplanation>
	</featureRow>
	<featureRow>
		<featureType>&nbsp;</featureType>
		<featureItem>plural</featureItem>
		<featureExplanation>plural in number</featureExplanation>
	</featureRow>
	<featureRow>
		<featureType>gender</featureType>
		<featureItem>masculine</featureItem>
		<featureExplanation>male gender</featureExplanation>
	</featureRow>
	<featureRow>
		<featureType>&nbsp;</featureType>
		<featureItem>feminine</featureItem>
		<featureExplanation>female gender</featureExplanation>
	</featureRow>
	<featureRow>
		<featureType>&nbsp;</featureType>
		<featureItem>neuter</featureItem>
		<featureExplanation>neuter gender</featureExplanation>
	</featureRow>
	<featureRow>
		<featureType>animacy</featureType>
		<featureItem>animate</featureItem>
		<featureExplanation>persons and animals</featureExplanation>
	</featureRow>
	<featureRow>
		<featureType>&nbsp;</featureType>
		<featureItem>-animate</featureItem>
		<featureExplanation>inanimate objects</featureExplanation>
	</featureRow>
	<featureRow>
		<featureType>class</featureType>
		<featureItem>class_##</featureItem>
		<featureExplanation>(replace ## with the class number up to 99)</featureExplanation>
	</featureRow>
</featureChart>

</instruction>
	<form section="pron" transparent="yes">
		<buttons>
			<button id="PronAgrBack" value="Back" goto="PronCase.htm"/>
			<button id="PronAgrNext" value="Next" goto="PronRefl.htm"/>
		</buttons>
	</form>
</page>
